version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/nodejs/Dockerfile"
    container_name: "trackeo_webserver"
    restart: 'always'
    links:
      - mongodb
    ports:
      - 80:3000
    volumes:
      - ./:/app

  mongodb:
    container_name: "trackeo_database"
    image: mongo
    ports:
      - 27017:27017
