version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./docker/nodejs/Dockerfile"
    container_name: "trackeo_webserver"
    restart: 'always'
    links:
      - mongodb
    ports:
      - 80:3000
    volumes:
      - ./:/app

  mongodb:
    container_name: "trackeo_database"
    image: mongo
    ports:
      - 27017:27017

  mosquitto:
      image: eclipse-mosquitto
      container_name: "trackeo_broker"
      volumes:
          - ./docker/mosquitto:/mosquitto
      ports:
          - 1883:1883
          - 9001:9001
